```{r}
if (!"occAssess" %in% installed.packages()) devtools::install_github("https://github.com/robboyd/occAssess")
library(occAssess)
library(rgbif)
library(readr)
library(rdrop2)
library(tidyverse)


library(DBI)
library(RPostgreSQL)

aws_con <- dbConnect(drv = "PostgreSQL",
                           dbname = "postgres", 
                           host = "postgres.cl0erzvvnfux.ap-northeast-1.rds.amazonaws.com", 
                           port = 5432, 
                           user = "kwizera_jvk", 
                           password = "Achibbo93...")
```

Get jpn invaded clean

```{r}
drop_url = "https://www.dropbox.com/sh/g7hbgbfyzocizmx/AADuSJWpCJ5LcMpbkNqLsWola/JPN/JPN-invaded-clean.csv?dl=1"
country = "jpn"
habitat = "Invaded-clean"

N = seq(from = 1, to = 1e9, by = 1000000)

options(timeout = 100000)

for (n in N) {
  gc()
  
  tryCatch({
  if(!("jpn_invaded_clean" %in% dbListTables(aws_con))){
    print("fetching new")
    
    value = read.csv(file = drop_url, header = T,
                    colClasses = c("NULL", "character","NULL", "NULL", "NULL", "NULL", 
                                   "numeric", "numeric", "NULL", "NULL", "numeric", "NULL",
                                   "numeric", "numeric", "NULL", "NULL", "NULL", "NULL", "NULL", "NULL", "NULL"), 
                   nrows = 1000000)
    rownames(value) = NULL
    
    print("uploading new")
    dbWriteTable(conn = aws_con, name = "jpn_invaded_clean", value = value)
  } 
  

    paste("reading", 1000000, "rows from", dbGetQuery(aws_con, "SELECT COUNT(*) FROM jpn_invaded_clean")$count) |> print()
  start = Sys.time()
    
  value = read.csv(file = drop_url, header = F,
                    colClasses = c("NULL", "character","NULL", "NULL", "NULL", "NULL", 
                                   "numeric", "numeric", "NULL", "NULL", "numeric", "NULL",
                                   "numeric", "numeric", "NULL", "NULL", "NULL", "NULL", "NULL", "NULL", "NULL"), 
                   nrows = 1000000, skip = dbGetQuery(aws_con, "SELECT COUNT(*) FROM jpn_invaded_clean")$count)
    
     if(!is_empty(value)) {
      rownames(value) = NULL
    
      db_columns = dbGetQuery(conn=aws_con, statement = "SELECT column_name 
                        FROM information_schema.columns WHERE table_name = 'jpn_invaded_clean' 
                        ORDER BY ordinal_position")
      colnames(value) = db_columns$column_name[2:7]
    
      
      paste("Updating", n, "to", (n + 1000000), "to AWS DB") |> print()
      dbWriteTable(conn = aws_con, 
                   name = "jpn_invaded_clean", 
                   value = value, 
                   overwrite = FALSE,
                   append = TRUE)
    } else {
      paste("row", n, "not found") |> print() 
    }
  
  finished = Sys.time()
  
  paste("completed in", (finished - start), "at", finished) |> print()
  })
}
```