```{r}
# db connection
source("~/Desktop/Documents/GitHub/bias assessment/connect_db.R")

# bias function
source("~/Desktop/Documents/GitHub/bias assessment/occAssess_bias_function.R")
```


```{r}
# Tables to analyse
tables = dbListTables(conn = aws_con)
tables = tables[-grep("lag", tables)][-grep("backbone", tables)] |> sort()

table_rows = function(table){
  query = paste("SELECT COUNT(*) AS rows, MIN(year) AS earliest_record FROM", table)
  query_output = dbGetQuery(aws_con, query)
  data.frame(table = table, rows = query_output$rows, earliest_record = query_output$earliest_record)
}

# check tables
table_list = list()
for (table in tables) {
  table_list[[table]] = table_rows(table = table)
}

# View tables
h = Reduce(dplyr::full_join, table_list) |> dplyr::arrange(table)
h |> dplyr::arrange(desc(rows)) -> h
tables = h$table
```


```{r}
# generate bias output files
for (db_table in tables) {
  Bias_assessment_function(db_table = db_table, con = aws_con, periods_length = 10)
}
```